fn main() {
    let config = slint_build::CompilerConfiguration::new().with_style("fluent".into());
    slint_build::compile_with_config("ui/app.slint", config).expect("Slint build failed");

    // Windows: embed the application icon and version info into the .exe.
    // (assets/icon.ico is generated by `cargo run -p cashflow-app --example icons`.)
    #[cfg(windows)]
    {
        let mut resource = winresource::WindowsResource::new();
        resource.set_icon("../../assets/icon.ico");
        resource.set("ProductName", "CashFlow");
        resource.set("FileDescription", "CashFlow – Lohnabrechnung");
        resource.set("CompanyName", "Ferdinand Hecker");
        resource.compile().expect("Windows resource");
    }
    println!("cargo:rerun-if-changed=../../assets/icon.ico");
}
