//! `public.employees`

use crate::database::Database;
use crate::error::{DataError, Result};
use crate::rest::Query;
use cashflow_core::{Address, Employee, EmployeeData, Gender, Rates, TransitionZone};
use chrono::NaiveDate;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use uuid::Uuid;

const TABLE: &str = "employees";
const COLUMNS: &str = "id,employer_id,personnel_number,first_name,last_name,birth_name,street,house_number,\
postal_code,city,birth_date,gender,nationality,social_security_number,tax_id,activity_key,contribution_group_key,\
person_group,transition_zone,occupation,health_insurer,employment_start,employment_end,monthly_salary,hourly_rate,\
rate_health,rate_pension,rate_u1,rate_u2,rate_insolvency,rate_flat_tax";

/// One row. `id` is only read (generated by the database), never written.
/// (No `#[serde(flatten)]`: it breaks number parsing with `arbitrary_precision`.)
#[derive(Deserialize, Serialize)]
struct Fields {
    #[serde(default, skip_serializing)]
    id: Option<Uuid>,
    employer_id: Uuid,
    personnel_number: String,
    first_name: String,
    last_name: String,
    birth_name: String,
    street: String,
    house_number: String,
    postal_code: String,
    city: String,
    birth_date: Option<NaiveDate>,
    gender: Option<String>,
    nationality: String,
    social_security_number: String,
    tax_id: String,
    activity_key: String,
    contribution_group_key: String,
    person_group: String,
    transition_zone: Option<i16>,
    occupation: String,
    health_insurer: String,
    employment_start: Option<NaiveDate>,
    employment_end: Option<NaiveDate>,
    monthly_salary: Option<Decimal>,
    hourly_rate: Option<Decimal>,
    rate_health: Decimal,
    rate_pension: Decimal,
    rate_u1: Decimal,
    rate_u2: Decimal,
    rate_insolvency: Decimal,
    rate_flat_tax: Decimal,
}

impl From<&EmployeeData> for Fields {
    fn from(data: &EmployeeData) -> Self {
        Fields {
            id: None,
            employer_id: data.employer_id,
            personnel_number: data.personnel_number.clone(),
            first_name: data.first_name.clone(),
            last_name: data.last_name.clone(),
            birth_name: data.birth_name.clone(),
            street: data.address.street.clone(),
            house_number: data.address.house_number.clone(),
            postal_code: data.address.postal_code.clone(),
            city: data.address.city.clone(),
            birth_date: data.birth_date,
            gender: data.gender.map(|g| g.code().to_string()),
            nationality: data.nationality.clone(),
            social_security_number: data.social_security_number.clone(),
            tax_id: data.tax_id.clone(),
            activity_key: data.activity_key.clone(),
            contribution_group_key: data.contribution_group_key.clone(),
            person_group: data.person_group.clone(),
            transition_zone: data.transition_zone.map(TransitionZone::code),
            occupation: data.occupation.clone(),
            health_insurer: data.health_insurer.clone(),
            employment_start: data.employment_start,
            employment_end: data.employment_end,
            monthly_salary: data.monthly_salary,
            hourly_rate: data.hourly_rate,
            rate_health: data.rates.health,
            rate_pension: data.rates.pension,
            rate_u1: data.rates.u1,
            rate_u2: data.rates.u2,
            rate_insolvency: data.rates.insolvency,
            rate_flat_tax: data.rates.flat_tax,
        }
    }
}

impl From<Fields> for Employee {
    fn from(f: Fields) -> Self {
        Employee {
            // Always present: every query selects `id`.
            id: f.id.unwrap_or_default(),
            data: EmployeeData {
                employer_id: f.employer_id,
                personnel_number: f.personnel_number,
                first_name: f.first_name,
                last_name: f.last_name,
                birth_name: f.birth_name,
                address: Address {
                    street: f.street,
                    house_number: f.house_number,
                    postal_code: f.postal_code,
                    city: f.city,
                },
                birth_date: f.birth_date,
                gender: f.gender.as_deref().and_then(Gender::from_code),
                nationality: f.nationality,
                social_security_number: f.social_security_number,
                tax_id: f.tax_id,
                activity_key: f.activity_key,
                contribution_group_key: f.contribution_group_key,
                person_group: f.person_group,
                transition_zone: f.transition_zone.and_then(TransitionZone::from_code),
                occupation: f.occupation,
                health_insurer: f.health_insurer,
                employment_start: f.employment_start,
                employment_end: f.employment_end,
                monthly_salary: f.monthly_salary,
                hourly_rate: f.hourly_rate,
                rates: Rates {
                    health: f.rate_health,
                    pension: f.rate_pension,
                    u1: f.rate_u1,
                    u2: f.rate_u2,
                    insolvency: f.rate_insolvency,
                    flat_tax: f.rate_flat_tax,
                },
            },
        }
    }
}

fn friendly(error: DataError) -> DataError {
    match error {
        DataError::Conflict { constraint: Some(name), .. } if name == "employees_personnel_number_key" => {
            DataError::Conflict { constraint: Some(name), message: "Diese Personalnummer ist bereits vergeben.".into() }
        }
        DataError::Reference(_) => DataError::Reference("Der gewählte Arbeitgeber existiert nicht mehr.".into()),
        other => other,
    }
}

/// How many monthly records would be deleted together with an employee.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct EmployeeRecordCounts {
    pub payroll_months: usize,
    pub time_months: usize,
}

impl Database {
    /// All employees, sorted by last and first name.
    pub async fn list_employees(&self) -> Result<Vec<Employee>> {
        let query = Query::new().select(COLUMNS).order("last_name.asc,first_name.asc,personnel_number.asc");
        let rows: Vec<Fields> = self.select(TABLE, &query).await?;
        Ok(rows.into_iter().map(Employee::from).collect())
    }

    pub async fn create_employee(&self, data: &EmployeeData) -> Result<Employee> {
        let row: Fields = self.insert(TABLE, &Fields::from(data)).await.map_err(friendly)?;
        Ok(row.into())
    }

    pub async fn update_employee(&self, id: Uuid, data: &EmployeeData) -> Result<Employee> {
        let filter = Query::new().eq("id", id).select(COLUMNS);
        let mut rows: Vec<Fields> = self.update(TABLE, &filter, &Fields::from(data)).await.map_err(friendly)?;
        Ok(rows.remove(0).into())
    }

    /// Deletes the employee together with all wage and time records.
    pub async fn delete_employee(&self, id: Uuid) -> Result<()> {
        match self.delete(TABLE, &Query::new().eq("id", id)).await? {
            0 => Err(DataError::NotFound),
            _ => Ok(()),
        }
    }

    /// Number of stored months, shown before deleting an employee.
    pub async fn count_employee_records(&self, id: Uuid) -> Result<EmployeeRecordCounts> {
        #[derive(Deserialize)]
        struct IdOnly {
            #[allow(dead_code)]
            id: Uuid,
        }
        let query = Query::new().select("id").eq("employee_id", id);
        let payroll: Vec<IdOnly> = self.select("payroll_records", &query).await?;
        let time: Vec<IdOnly> = self.select("time_records", &query).await?;
        Ok(EmployeeRecordCounts { payroll_months: payroll.len(), time_months: time.len() })
    }
}
