//! `public.payroll_records` and `public.time_records`: one row per employee and month.

use crate::database::Database;
use crate::error::{DataError, Result};
use crate::rest::Query;
use cashflow_core::payroll::{Calculation, Contributions};
use cashflow_core::{PayrollEntry, PayrollRecord, Period, Rates, TimeEntry, TimeRecord};
use chrono::NaiveDate;
use rust_decimal::Decimal;
use serde::{Deserialize, Serialize};
use std::collections::HashSet;
use uuid::Uuid;

const PAYROLL: &str = "payroll_records";
const TIME: &str = "time_records";
const PERIOD_KEY: &str = "employee_id,year,month";

fn period(year: i32, month: u32) -> Result<Period> {
    Period::new(year, month).map_err(|error| DataError::Decode(error.to_string()))
}

// -- Wage records ---------------------------------------------------------------

#[derive(Deserialize)]
struct PayrollRow {
    id: Uuid,
    employee_id: Uuid,
    year: i32,
    month: u32,
    statement_date: NaiveDate,
    base_pay: Decimal,
    extra_pay: Decimal,
    payout: Decimal,
    rate_health: Decimal,
    rate_pension: Decimal,
    rate_u1: Decimal,
    rate_u2: Decimal,
    rate_insolvency: Decimal,
    rate_flat_tax: Decimal,
    gross_total: Decimal,
    amount_health: Decimal,
    amount_pension: Decimal,
    amount_u1: Decimal,
    amount_u2: Decimal,
    amount_insolvency: Decimal,
    amount_flat_tax: Decimal,
    total_contribution: Decimal,
}

impl TryFrom<PayrollRow> for PayrollRecord {
    type Error = DataError;

    fn try_from(row: PayrollRow) -> Result<Self> {
        Ok(PayrollRecord {
            id: row.id,
            entry: PayrollEntry {
                employee_id: row.employee_id,
                period: period(row.year, row.month)?,
                statement_date: row.statement_date,
                base_pay: row.base_pay,
                extra_pay: row.extra_pay,
                payout: row.payout,
                rates: Rates {
                    health: row.rate_health,
                    pension: row.rate_pension,
                    u1: row.rate_u1,
                    u2: row.rate_u2,
                    insolvency: row.rate_insolvency,
                    flat_tax: row.rate_flat_tax,
                },
            },
            calculation: Calculation {
                gross_total: row.gross_total,
                contributions: Contributions {
                    health: row.amount_health,
                    pension: row.amount_pension,
                    u1: row.amount_u1,
                    u2: row.amount_u2,
                    insolvency: row.amount_insolvency,
                    flat_tax: row.amount_flat_tax,
                },
                total_contribution: row.total_contribution,
            },
        })
    }
}

/// Only the input columns: amounts are generated by the database.
#[derive(Serialize)]
struct PayrollWrite {
    employee_id: Uuid,
    year: i32,
    month: u32,
    statement_date: NaiveDate,
    base_pay: Decimal,
    extra_pay: Decimal,
    payout: Decimal,
    rate_health: Decimal,
    rate_pension: Decimal,
    rate_u1: Decimal,
    rate_u2: Decimal,
    rate_insolvency: Decimal,
    rate_flat_tax: Decimal,
}

impl From<&PayrollEntry> for PayrollWrite {
    fn from(entry: &PayrollEntry) -> Self {
        PayrollWrite {
            employee_id: entry.employee_id,
            year: entry.period.year(),
            month: entry.period.month(),
            statement_date: entry.statement_date,
            base_pay: entry.base_pay,
            extra_pay: entry.extra_pay,
            payout: entry.payout,
            rate_health: entry.rates.health,
            rate_pension: entry.rates.pension,
            rate_u1: entry.rates.u1,
            rate_u2: entry.rates.u2,
            rate_insolvency: entry.rates.insolvency,
            rate_flat_tax: entry.rates.flat_tax,
        }
    }
}

// -- Time records ----------------------------------------------------------------

#[derive(Deserialize)]
struct TimeRow {
    id: Uuid,
    employee_id: Uuid,
    year: i32,
    month: u32,
    hours_worked: Decimal,
    extra_hours: Decimal,
    vacation_days: Decimal,
    sick_days: Decimal,
}

impl TryFrom<TimeRow> for TimeRecord {
    type Error = DataError;

    fn try_from(row: TimeRow) -> Result<Self> {
        Ok(TimeRecord {
            id: row.id,
            entry: TimeEntry {
                employee_id: row.employee_id,
                period: period(row.year, row.month)?,
                hours_worked: row.hours_worked,
                extra_hours: row.extra_hours,
                vacation_days: row.vacation_days,
                sick_days: row.sick_days,
            },
        })
    }
}

#[derive(Serialize)]
struct TimeWrite {
    employee_id: Uuid,
    year: i32,
    month: u32,
    hours_worked: Decimal,
    extra_hours: Decimal,
    vacation_days: Decimal,
    sick_days: Decimal,
}

impl From<&TimeEntry> for TimeWrite {
    fn from(entry: &TimeEntry) -> Self {
        TimeWrite {
            employee_id: entry.employee_id,
            year: entry.period.year(),
            month: entry.period.month(),
            hours_worked: entry.hours_worked,
            extra_hours: entry.extra_hours,
            vacation_days: entry.vacation_days,
            sick_days: entry.sick_days,
        }
    }
}

/// Which months of a year already have wage / time records (for the overview).
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RecordedMonths {
    pub payroll: HashSet<(Uuid, u32)>,
    pub time: HashSet<(Uuid, u32)>,
}

impl RecordedMonths {
    pub fn has_payroll(&self, employee_id: Uuid, month: u32) -> bool {
        self.payroll.contains(&(employee_id, month))
    }

    pub fn has_time(&self, employee_id: Uuid, month: u32) -> bool {
        self.time.contains(&(employee_id, month))
    }
}

fn period_filter(employee_id: Uuid, period: Period) -> Query {
    Query::new().eq("employee_id", employee_id).eq("year", period.year()).eq("month", period.month())
}

fn year_filter(employee_id: Uuid, year: i32) -> Query {
    Query::new().eq("employee_id", employee_id).eq("year", year).order("month.asc")
}

impl Database {
    /// The wage record of one month, if recorded.
    pub async fn payroll_record(&self, employee_id: Uuid, period: Period) -> Result<Option<PayrollRecord>> {
        let row: Option<PayrollRow> =
            self.select_optional(PAYROLL, &period_filter(employee_id, period).select("*")).await?;
        row.map(PayrollRecord::try_from).transpose()
    }

    /// All wage records of one employee in one year, ordered by month.
    pub async fn payroll_records_of_year(&self, employee_id: Uuid, year: i32) -> Result<Vec<PayrollRecord>> {
        let rows: Vec<PayrollRow> = self.select(PAYROLL, &year_filter(employee_id, year).select("*")).await?;
        rows.into_iter().map(PayrollRecord::try_from).collect()
    }

    /// Creates or replaces the wage record of the entry's month.
    pub async fn save_payroll(&self, entry: &PayrollEntry) -> Result<PayrollRecord> {
        let row: PayrollRow =
            self.upsert(PAYROLL, PERIOD_KEY, &PayrollWrite::from(entry)).await.map_err(missing_employee)?;
        row.try_into()
    }

    pub async fn delete_payroll_record(&self, id: Uuid) -> Result<()> {
        match self.delete(PAYROLL, &Query::new().eq("id", id)).await? {
            0 => Err(DataError::NotFound),
            _ => Ok(()),
        }
    }

    /// The time record of one month, if recorded.
    pub async fn time_record(&self, employee_id: Uuid, period: Period) -> Result<Option<TimeRecord>> {
        let row: Option<TimeRow> = self.select_optional(TIME, &period_filter(employee_id, period).select("*")).await?;
        row.map(TimeRecord::try_from).transpose()
    }

    /// All time records of one employee in one year, ordered by month.
    pub async fn time_records_of_year(&self, employee_id: Uuid, year: i32) -> Result<Vec<TimeRecord>> {
        let rows: Vec<TimeRow> = self.select(TIME, &year_filter(employee_id, year).select("*")).await?;
        rows.into_iter().map(TimeRecord::try_from).collect()
    }

    /// Creates or replaces the time record of the entry's month.
    pub async fn save_time(&self, entry: &TimeEntry) -> Result<TimeRecord> {
        let row: TimeRow = self.upsert(TIME, PERIOD_KEY, &TimeWrite::from(entry)).await.map_err(missing_employee)?;
        row.try_into()
    }

    pub async fn delete_time_record(&self, id: Uuid) -> Result<()> {
        match self.delete(TIME, &Query::new().eq("id", id)).await? {
            0 => Err(DataError::NotFound),
            _ => Ok(()),
        }
    }

    /// Recorded months of all employees in `year` (two small requests).
    pub async fn recorded_months(&self, year: i32) -> Result<RecordedMonths> {
        #[derive(Deserialize)]
        struct Month {
            employee_id: Uuid,
            month: u32,
        }
        let query = Query::new().select("employee_id,month").eq("year", year);
        let payroll: Vec<Month> = self.select(PAYROLL, &query).await?;
        let time: Vec<Month> = self.select(TIME, &query).await?;
        Ok(RecordedMonths {
            payroll: payroll.into_iter().map(|m| (m.employee_id, m.month)).collect(),
            time: time.into_iter().map(|m| (m.employee_id, m.month)).collect(),
        })
    }
}

fn missing_employee(error: DataError) -> DataError {
    match error {
        DataError::Reference(_) => DataError::Reference("Der Mitarbeiter existiert nicht mehr.".into()),
        other => other,
    }
}
